# Azure DevOps pipeline for Analog Core

trigger:
- develop
- production
- feature/**/**

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: file-creator@5
  inputs:
    filepath: 'coffeecard/CoffeeCard.WebApi/www.analogio.dk.pfx'
    filecontent: 'empty file'
- task: file-creator@5
  inputs:
    filepath: 'coffeecard/CoffeeCard.Console.Refund/appsettings.json'
    filecontent: 'empty file'
- task: file-creator@5
  inputs:
    filepath: 'coffeecard/CoffeeCard.Console.Refund/www.analogio.dk.pfx'
    filecontent: 'empty file'

- task: DotNetCoreCLI@2
  displayName: 'Restore solution'
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'AnalogIO SonarCloud'
    organization: 'analogio'
    scannerMode: 'MSBuild'
    projectKey: 'AnalogIO_analog-core'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    
- task: DotNetCoreCLI@2
  displayName: 'Execute Unit tests'
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--collect "Code Coverage"'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'